# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [3]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [4]:
#todo: 
array1 = np.array([0,1,2,3,4,5,6,7,8,9])
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [5]:
#todo:
cero1 = np.zeros(5)
cero1[2] = 5
cero1

array([0., 0., 5., 0., 0.])

**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [6]:
#todo: 
matris1 = np.random.choice([0,1],size=(3,3,3))
matris1

array([[[1, 1, 1],
        [1, 0, 1],
        [0, 0, 1]],

       [[0, 1, 1],
        [0, 0, 1],
        [1, 1, 0]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]])

**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [38]:
#todo:
arraySuma = np.array([10,30,30,40,50])
arraySumado = arraySuma + np.array(5)
print('sumado por 5: ',arraySumado) 
arrayMultiplicado = arraySuma * np.array(randint(0,100))
print('multiplicados por numero aleatorios: ',arrayMultiplicado) 

sumado por 5:  [15 35 35 45 55]
multiplicados por numero aleatorios:  [ 480 1440 1440 1920 2400]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [8]:
#todo:

matriz_cero = np.zeros((4,4))

np.fill_diagonal(matriz_cero,1)

matriz_cero

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [14]:
#todo: 
array_pares = np.arange(0, 21, 2)
print("Array de números pares:", array_pares)


suma = array_pares + 2
resta = array_pares - 2
multiplicacion = array_pares * 2
division = array_pares / 2  

print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)


Array de números pares: [ 0  2  4  6  8 10 12 14 16 18 20]
Suma: [ 2  4  6  8 10 12 14 16 18 20 22]
Resta: [-2  0  2  4  6  8 10 12 14 16 18]
Multiplicación: [ 0  4  8 12 16 20 24 28 32 36 40]
División: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
